# Generated by Django 3.2.9 on 2021-12-02 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrangement_fee_pct', models.FloatField(default=0)),
                ('interest_pct', models.FloatField(default=0)),
                ('non_utilisation_fee_pct', models.FloatField(default=0)),
                ('exit_fee_pct', models.FloatField(default=0)),
                ('ltv_covenant', models.FloatField(default=0)),
                ('ltc_covenant', models.FloatField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('maturity_date', models.DateField(default=datetime.date.today)),
                ('facility_schedule', models.JSONField(default=dict)),
                ('funding_schedule', models.JSONField(default=dict)),
                ('equity_required', models.FloatField(default=0)),
                ('facility_amount', models.FloatField(default=0)),
                ('building', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cre_finance.building')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('Acquisition costs', 'Acquisition costs'), ('Construction costs', 'Construction costs'), ('Professional fees', 'Professional fees')], default='Construction costs', max_length=100)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(default=datetime.date.today)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cre_finance.building')),
            ],
        ),
    ]
