# Generated by Django 4.0.2 on 2022-02-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre_finance', '0002_alter_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
