# Generated by Django 4.0.2 on 2022-02-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cre_finance', '0003_alter_sponsor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='building',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='property',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='arrangement_fee_pct',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='building',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='equity_required',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='exit_fee_pct',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='facility_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='facility_schedule',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='funding_schedule',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_pct',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='ltc_covenant',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='ltv_covenant',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='non_utilisation_fee_pct',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cre_finance.broker'),
        ),
        migrations.AddField(
            model_name='loan',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cre_finance.property'),
        ),
        migrations.AddField(
            model_name='loan',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cre_finance.sponsor'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
