# Generated by Django 4.0.2 on 2022-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre_finance', '0004_remove_cost_building_remove_deal_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
