# Generated by Django 4.0.2 on 2022-02-25 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cre_finance', '0006_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cre_finance.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('Acquisition costs', 'Acquisition costs'), ('Construction costs', 'Construction costs'), ('Professional fees', 'Professional fees')], default='Construction costs', max_length=100)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(default=datetime.date.today)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cre_finance.building')),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='loan',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cre_finance.building'),
        ),
    ]
