# Generated by Django 4.0.2 on 2022-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre_finance', '0008_rename_type_cost_category_cost_curve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
